language: c
jobs:
  include:
    - os: linux
      env: GENERATOR="Unix Makefiles"
      sudo: required
      before_script:
        - test -e /usr/bin/cmake || sudo ln -s $(which cmake) /usr/bin/cmake
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp
          DO_CMD=sudo bash
    - os: osx
      env: GENERATOR="Unix Makefiles"
      before_script:
        curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp
        DO_CMD=sudo bash
addons:
  apt:
    packages:
      - cmake
script:
  - mkdir prefix
  - mkdir build
  - cd build
  - cmake -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/prefix
    ..
  - cmake --build . --config Release
  - ctest --output-on-failure -C Release
  - cmake --build . --config Release --target install
  - test -e $TRAVIS_BUILD_DIR/prefix/include/liknorm/liknorm.h
  - test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/liknorm/liknorm-config.cmake
  - test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/liknorm/liknorm-targets-release.cmake
  - test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/liknorm/liknorm-targets.cmake
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then otool -l $TRAVIS_BUILD_DIR/prefix/lib/libliknorm.dylib | grep -q LC_RPATH; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then test -e $TRAVIS_BUILD_DIR/prefix/lib/libliknorm.so; fi
  - cd $TRAVIS_BUILD_DIR
  - git clean -xdf
notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
